### ISSUE TITLE
Minor UI fixes and improvements

### ISSUE THREAD

**Issue by joulei** [project-robius/robrix#137]
- [x] Gray out icons of not yet implemented features
- [x] Minor vertical mis-alignment on small state items
- [x] Missing/squashed left padding on user profile sliding pane 
- [x] Misaligned code block background, miscellaneous vertical spacing issues
- [x] Change the hover bg color for Message to have starker contrast with background color of Html blocks (`draw_block: { quote_bg_color: ... }`)
- [x] Text input's text is invisible due to color matching the background
- [x] Update user profile colors to match the general UI theme

- [x] Change text color in html block bg in RoomPreviewSelected, to `MESSAGE_TEXT_COLOR`
- [x] Make rooms list sidebar narrower
- [ ] Make the border between the "replying preview" and the bottom of the timeline view more distinct, either via a shadow or different bg colors

- Display the message timestamp next to username. Edit: this will be worked on separately.

**Comment by kevinaboos** [comment]
Need to fix the color of the html quote block bg  in the RoomPreviewSelected:

here's an example of it unselected:
<img width="394" alt="image" src="https://github.com/user-attachments/assets/44934769-75de-4a6c-9b92-ffc10c994fe0">

and here it is when selected -- it's white text on a near-white bg
<img width="380" alt="image" src="https://github.com/user-attachments/assets/0afad6d5-4460-4907-8318-6f6cf1e9dc0b">
