### ISSUE TITLE
Improve the `typing_notice` view with animations

### ISSUE THREAD

**Issue by ZhangHanDong** [project-robius/robrix#155]
For the context of this issue, please refer to #99  and [PR 147](https://github.com/project-robius/robrix/pull/147#issuecomment-2365230896)  . 

The functions to be implemented under this issue are:

- [x] Make the display interface of the ongoing notification more readable.
- [x] Add an animated ellipsis after the "Users are typing" label
- [ ] animate the `typing_notice` view in and out of the room screen view, such as by having it fold up or fade upwards from the bottom

**Comment by alanpoon** [comment]
I am looking at this issue
