### ISSUE TITLE
Add this to README

### ISSUE THREAD

**Issue by chagai95** [project-robius/robrix#156]
sudo apt-get update
sudo apt-get install libssl-dev pkg-config llvm clang libclang-dev binfmt-support libxcursor-dev libx11-dev libasound2-dev libpulse-dev

**Comment by Demolemon11** [comment]
Yes, It just not only shortages of that two libraries

**Comment by Demolemon11** [comment]
> sudo apt-get update sudo apt-get install libssl-dev pkg-config llvm clang libclang-dev binfmt-support libxcursor-dev libx11-dev libasound2-dev libpulse-dev

You can pull a request to fix the READMA : )
