### ISSUE TITLE
When any changes are saved, it jumps to the login_screen page and it can't login.

### ISSUE THREAD

**Issue by tyreseluo** [project-robius/robrix#209]
When any changes are saved, it jumps to the login_screen page and it can't login. You have to `cargo run` again. It's hard to debug.

**Comment by joulei** [comment]
@tyreseluo with changes are saved do you mean live reloading? (i.e. modifying some code and then the app jumps into login)

**Comment by tyreseluo** [comment]
yep, not only changes the live code, any file changes when their saved. It will jump to the login page. I think the reason is that the judgment value of the login page is not saved when re-live reloading.

**Comment by joulei** [comment]
> yep, not only changes the live code, any file changes when their saved. It will jump to the login page. I think the reason is that the judgment value of the login page is not saved when re-live reloading.

Right, that seems to be the problem. I'll take a look.
