### ISSUE TITLE
Apply a yellow background highlight to messages that mention the current user

### ISSUE THREAD

**Issue by kevinaboos** [project-robius/robrix#229]
This is pretty self-explanatory; the goal is to attract the user's attention to a message that mentions them.

We can define a DSL constant called `COLOR_HIGHLIGHT_MENTION_MESSAGE` or something similar such that the color can be easily changed, but my initial preference is to set this to a lighter/pale yellow color.

Messages are already highlighted in two situations: upon hovering over them, and upon the completion of a smooth scroll up to a "target" message (e.g., a replied-to message).
This color should not fully overwrite those effect colors, but should be mixed with them. This is necessary in order to allow other animation effects to still be applied to a message that mentions the current user.

Note that this background highlight effect can also be applied to messages that are  _replying_ to a message sent by the current user; however, this isn't strictly necessary. 
Discord _does_ do this, for example: 
<img width="643" alt="image" src="https://github.com/user-attachments/assets/dde6dfc1-fe25-4f9a-bc12-0362865bcf24">

while Element only does it for _non-reply_ messages that directly mention the user. (note that Element also colors the text red, which is **not** a choice we should make):
<img width="638" alt="image" src="https://github.com/user-attachments/assets/74fe0659-eec8-48c2-aedc-f249a5c7548d">

**Comment by Demolemon11** [comment]
I am looking at this

**Comment by Demolemon11** [comment]
Do you mean that the color of `other reply to self` area should consist of a fixed yellow color mixed with the RoomScreen background color, right?

**Comment by Demolemon11** [comment]
![image](https://github.com/user-attachments/assets/e028b7ac-e6e6-471d-af00-aa4202ea9ba0)

#### Which one am I supposed to modify?

**Comment by Demolemon11** [comment]
So, there are three cases:
- `other` -> `other`
- `other` -> `self`
- `self` -> `other`

What I need to handle is just `other` -> `self`, right?

**Comment by Demolemon11** [comment]
![image](https://github.com/user-attachments/assets/c040082e-6b70-47af-be04-9528d89e657a)


#### This is the logic of `self` -> `other`, right?

**Comment by Demolemon11** [comment]
Do you mean both background of "reply area" & all the widgets inside "reply area" should be consisted of a fixed yellow color, right?

**Comment by kevinaboos** [comment]
This isn't related Reply Preview, it's related to the Message widget struct. See that widget and how the hover color is implemented there. That's the only widget you'll need to deal with.

**Comment by Demolemon11** [comment]
Got it, thanks

**Comment by Demolemon11** [comment]
![image](https://github.com/user-attachments/assets/542e6e50-edb5-411f-a8ce-8c911f8ead33)

These are the widgets of `<PortalList>` under `Timeline`.
The `other`->`self` is a  `<Message>` , right?

**Comment by Demolemon11** [comment]
![image](https://github.com/user-attachments/assets/29103935-425c-48b2-8f63-18766a9f0bef)

I found it, the `<ReplyPreviewContent>` was reused for two times in order that they both widget so similar(avater size, font size) for what mentioned above.

What I need to modify is just `<RepliedToMessage>`.

**Comment by Demolemon11** [comment]
![image](https://github.com/user-attachments/assets/1a25920a-8237-4d03-b417-192112e22020)
what's this (`reply_preview_body`)?

**Comment by Demolemon11** [comment]
![Screenshot from 2024-11-04 23-45-02](https://github.com/user-attachments/assets/beba4d6f-8ede-4026-b4eb-7543155c0f2b)

Here we can get sender's id, but how can we get the receiver's ID , who is be replied.

**Comment by Demolemon11** [comment]
![image](https://github.com/user-attachments/assets/30eb70b9-6c5a-4104-9725-cb0fd1230866)
what's this? Can I get id the one is replioed?

**Comment by kevinaboos** [comment]
First up, kindly refrain from posting screenshots of code; you can either copy the relevant regions as text, or provide a link to the code (see below for an example).

Second, this isn't really a real-time chat platform, so if you want to have a discussion in that format (with lots of quick messages just stating your thoughts), then let's use the Robrix matrix room or our WeChat channel for that.

Third, this issue does not have anything to do with modifying the content or look of a ReplyPreview, ReplyPreviewContent, or anything that has to do with reply UI views. You only need to modify the `struct Message` widget, which is here:, like so: https://github.com/project-robius/robrix/blob/185459f8cfb6443e38c57149c6d7afd796d770e8/src/home/room_screen.rs#L3142

If you want to continue working on this issue, please re-read the main description at the top of this page and then feel free to ask any clarifying questions. Based on your questions above it seems like you're not quite clear on what this issue is about; that's no problem at all -- I'd encourage you to pick up a different issue if you'd like to contribute in another way. 

As a hint to get you started, all you really need to do is add a boolean value to the `Message` struct called something like `mentions_user`, which you can then set as part of the `Message::set_data()` function here: https://github.com/project-robius/robrix/blob/185459f8cfb6443e38c57149c6d7afd796d770e8/src/home/room_screen.rs#L3237

Then, in the code that handles drawing the background of a `Message`, you'll need to utilize that `mentions_user` boolean value to determine what the background color of the Message should be -- normal or yellow. 
https://github.com/project-robius/robrix/blob/185459f8cfb6443e38c57149c6d7afd796d770e8/src/home/room_screen.rs#L309-L323

**Comment by Demolemon11** [comment]
I got it. Of course I 'll keep on doing this, thanks very much!

**Comment by kevinaboos** [comment]
Addressed by #240

**Comment by kevinaboos** [comment]
Closed by #240
