### ISSUE TITLE
Problems with Room list rendering

### ISSUE THREAD

**Issue by tyreseluo** [project-robius/robrix#233]
Issue From:  https://github.com/project-robius/robrix/issues/123

@joulei It seems that the room_list rendering problem we discussed last time still exists?Can you take a look and help me describe the problem?
@kevinaboos Already using your latest commit, I have push the draft code to PR #232.

![yAHLNmoBbr](https://github.com/user-attachments/assets/242d49e1-6554-4491-b471-efc7f23fe8f7)

**Comment by kevinaboos** [comment]
this is a makepad bug that was introduced a couple of weeks ago and recently reverted. I have now updated our dependency on makepad to depend on a version that _shouldn't_ have this problem. 

I'm no longer able to replicate it as of #236 being merged in, but please test it yourself and let me know.

**Comment by tyreseluo** [comment]
Ok,I will do that.
