### ISSUE TITLE
UI Bug:  The pop-up box of the User verification icon in the upper left corner is obscured by the Rooms UI

### ISSUE THREAD

**Issue by ZhangHanDong** [project-robius/robrix#299]
As mentioned in the title, the screenshot is as follows.

![image](https://github.com/user-attachments/assets/552dc786-699f-4f94-927b-a2d74f612cb4)

 The bug appears on the MacOS, works normally on the Linux, and Windows.

**Comment by kevinaboos** [comment]
yeah, unfortunately this is a known issue with the Makepad dock widget (I think, not 100% sure of the root cause). I mentioned it to Julian & Rik a few months ago but hasn't yet been addressed.
