### ISSUE TITLE
Consider setting the height of the `RoomPreview` widget to a fixed height.

### ISSUE THREAD

**Issue by tyreseluo** [project-robius/robrix#300]
## Issue Content

Currently, the height of our `RoomPreview` widget is calculated from the child widgets, which causes the `RoomPreview` widget to be too tall when the user enters a long message, resulting in a very redundant room list.

Consider setting the height of the `RoomPreview` widget to a fixed height and displaying an ellipsis when the user sends a long message.

## Impact on other PRs

- Search bar of the rooms list top #298 , The variable height is causing problems with the search_bar functionality, and I'm not sure what's currently going on.

**Comment by kevinaboos** [comment]
We already did this, unless I misunderstand the issue. I haven't added an ellipsis yet though.

**Comment by kevinaboos** [comment]
Here: https://github.com/project-robius/robrix/pull/296

**Comment by tyreseluo** [comment]
But so far I haven't investigated why the height of the RoomPreview still affects the functionality of the search bar, it's very strange. So far if you don't set the height of RoomPreview to a fixed height, the search bar filters the room list differently, even though the filter logic is actually correct!

**Comment by kevinaboos** [comment]
that's an unrelated issue then, since you're reporting a bug or misbehavior in your new PR that hasn't yet been accepted. Thus, I'll close this and contain these discussions in #298 itself.
