### ISSUE TITLE
Support sending replies to a specific message

### ISSUE THREAD

**Issue by kevinaboos** [project-robius/robrix#83]
This feature will enable the user to reply to a particular message. Currently Robrix only supports sending a standalone message that is not in-reply-to anything.

## Implementation Approach
This requires modifying the UI in two places:
1. adding a reply button to each message
2. adding a "Replying-to" preview above the message input box

### Reply button
For the Makepad DSL components, we can add a Reply IconButton to all of the `Message`-like views. Most likely, the best place to add this is as part of the `MessageMenu`, which itself needs to be redesigned entirely.

By default, this view would be marked as `visible: false`, and would only be set to visible upon hover, or by showing a context menu when right-clicking / long-pressing on a message. I think the best option is to show this on the upper-right corner of the message, which is what both Element and Discord do (see the Examples section below).

Note that we should only show the reply button if the message can be replied to, which can be determined via [this function](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/timeline/struct.EventTimelineItem.html#method.can_be_replied_to).

> Makepad doesn't yet have built-in support for context menus, so it is probably best to _initially_ make the buttons (and the MessageMenu) visible at all times (instead of just upon hover).
> 
> Makepad also doesn't yet support gestures, but eventually when it does, we'll want to add a swipe gesture to reply to a message too.

### Replying-to message preview
Once the reply button has been pressed, we should add a view right above the `message_input` text input box (at the bottom of the `RoomScreen`) that shows a preview of the message that the user is about to reply to. We could likely re-use the `ReplyPreview` suggested in issue #82 for this.

In addition, we need a cancel `(X)` button that sits at the far right side of the reply preview, which allows the user to cancel the reply action, which will make the current message being composed in the `message_input` text box act as a regular standalone message.

Here's an example of how Element displays this "Replying to" preview:

<img width="475" alt="image" src="https://github.com/user-attachments/assets/f003f949-235a-457b-9e30-3dd000dba825">

### Actually sending the message
Currently, messages are sent in the code here: https://github.com/project-robius/robrix/blob/a5ff746085dd381459844025ff06150664dd323e/src/home/room_screen.rs#L578

It should be straightforward to augment this to support sending a reply message. Currently, the actual message is sent here: https://github.com/project-robius/robrix/blob/a5ff746085dd381459844025ff06150664dd323e/src/sliding_sync.rs#L265, but we should be able to easily add another case where we use [`send_reply()` function](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_ui/timeline/struct.Timeline.html#method.send_reply) provided by the Matrix SDK.

## Examples
Here's how Element on desktop shows a message menu upon hovering over it, with the reply button in the middle:

<img width="587" alt="image" src="https://github.com/user-attachments/assets/3b1efa76-bdd2-43c1-ac25-68511efea5cc">

Here's how Discord shows the reply button:

<img width="578" alt="image" src="https://github.com/user-attachments/assets/8a19862a-e002-4f29-a74e-0c84b36276e8">

**Comment by fmzbl** [comment]
Will be working on this!

**Comment by kevinaboos** [comment]
Implemented in #104
